version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "samstack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zrap0pkkk7sj"
s3_prefix = "samstack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
